name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # This will sync your fork every day at midnight

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Sync the fork
      run: |
        git remote add upstream https://github.com/ultralytics/ultralytics
        git fetch upstream
        git checkout main # or whatever your default branch is
        git merge upstream/main # again, replace with the default branch name if it's different
        git push
